name: Redis
tabs:
- name: main
  label: Info
  sections:
  - name: section_one
    contents: 
    - type: heading
      label: "Important Note: Internal Traffic Only"
    - type: subtitle
      label: "This instance of Redis is only exposed to internal traffic and can only be reached from other services running on Porter. A connection string for this database will be shown after the template is deployed."